spring.profiles: local
server:
  port: 9000
spring.data.mongodb.database: dsmc
spring.data.mongodb.uri: mongodb://localhost:27017
security.user.password: password

app.mailgun.endpoint: https://api.mailgun.net/v3/24sixty.io/messages
app.mailgun.clientId: api