spring.profiles.active: dev
management.add-application-context-header: false
server.server-header: unspecified
app.passcode.length: 6
app.passcode.emailTemplateId: onboarding-company-account-verification

spring.data.mongodb.database: ${spring.data.mongodb.database}
spring.data.mongodb.uri: ${spring.data.mongodb.uri}

app.security.encryption.key: ${app.security.encryption.key}
app.security.encryption.salt: ${app.security.encryption.salt}
app.security.encryption.algo: ${app.security.encryption.algo}

app.mailgun.clientId: ${app.mailgun.clientId}
app.mailgun.apikey: ${app.mailgun.apikey}
app.mailgun.endpoint: ${app.mailgun.endpoint}

app.security.admin.username: ${app.security.admin.username}
app.security.admin.password: ${app.security.admin.password}
app.security.admin.role: ${app.security.admin.role}
app.security.token.lifetime: ${app.security.token.lifetime}